trigger:
  - main

pool:
  name: 'Default'

variables:
  dockerRepository: 'miracle2412/lab1-cicd'
  dockerTag: 'latest'

steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.12'
    inputs:
      versionSpec: '3.12'

  - script: |
      python -m ensurepip --upgrade
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m pytest -v
    displayName: 'Run unit tests'

  - task: Docker@2
    displayName: 'Build and push Docker image'
    inputs:
      containerRegistry: 'dockerhub-connection'
      repository: '$(dockerRepository)'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      tags: |
        $(dockerTag)